//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPoolDay
    {
        public int CarPoolDayID { get; set; }
        public int CarPoolID { get; set; }
        public int DayOfWeekID { get; set; }
    
        public virtual CarPool CarPool { get; set; }
        public virtual DaysOfWeek DaysOfWeek { get; set; }
    }
}
