USE [master]
GO
/****** Object:  Database [CoMute]    Script Date: 2015/09/25 08:37:28 ******/
CREATE DATABASE [CoMute]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoMute', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CoMute.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CoMute_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CoMute_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CoMute] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoMute].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CoMute] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CoMute] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CoMute] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CoMute] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CoMute] SET ARITHABORT OFF 
GO
ALTER DATABASE [CoMute] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CoMute] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [CoMute] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CoMute] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CoMute] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CoMute] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CoMute] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CoMute] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CoMute] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CoMute] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CoMute] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CoMute] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CoMute] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CoMute] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CoMute] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CoMute] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CoMute] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CoMute] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CoMute] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CoMute] SET  MULTI_USER 
GO
ALTER DATABASE [CoMute] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CoMute] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CoMute] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CoMute] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [CoMute]
GO
/****** Object:  Table [dbo].[CarPoolDays]    Script Date: 2015/09/25 08:37:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarPoolDays](
	[CarPoolID] [int] NOT NULL,
	[DayOfWeekID] [int] NOT NULL,
 CONSTRAINT [PK_CarPoolDays] PRIMARY KEY CLUSTERED 
(
	[CarPoolID] ASC,
	[DayOfWeekID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CarPools]    Script Date: 2015/09/25 08:37:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CarPools](
	[CarPoolID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[departureTime] [nchar](10) NOT NULL,
	[expectedArrivalTime] [nchar](10) NOT NULL,
	[origin] [varchar](max) NOT NULL,
	[destination] [varchar](max) NOT NULL,
	[seatsAvailable] [int] NOT NULL,
	[notes] [varchar](max) NULL,
	[created] [datetime] NOT NULL,
 CONSTRAINT [PK_CarPools] PRIMARY KEY CLUSTERED 
(
	[CarPoolID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DayOfWeek]    Script Date: 2015/09/25 08:37:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DayOfWeek](
	[DayOfWeekID] [int] NOT NULL,
	[nameOfDay] [varchar](10) NOT NULL,
 CONSTRAINT [PK_DayOfWeek] PRIMARY KEY CLUSTERED 
(
	[DayOfWeekID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Users]    Script Date: 2015/09/25 08:37:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[firstName] [varchar](30) NOT NULL,
	[lastName] [varchar](30) NOT NULL,
	[emailAddress] [varchar](128) NOT NULL,
	[phoneNumber] [varchar](12) NOT NULL,
	[password] [varchar](255) NOT NULL,
	[active] [bit] NOT NULL,
	[created] [datetime] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[DayOfWeek] ([DayOfWeekID], [nameOfDay]) VALUES (0, N'Sunday')
GO
INSERT [dbo].[DayOfWeek] ([DayOfWeekID], [nameOfDay]) VALUES (1, N'Monday')
GO
INSERT [dbo].[DayOfWeek] ([DayOfWeekID], [nameOfDay]) VALUES (2, N'Tuesday')
GO
INSERT [dbo].[DayOfWeek] ([DayOfWeekID], [nameOfDay]) VALUES (3, N'Wednesday')
GO
INSERT [dbo].[DayOfWeek] ([DayOfWeekID], [nameOfDay]) VALUES (4, N'Thursday')
GO
INSERT [dbo].[DayOfWeek] ([DayOfWeekID], [nameOfDay]) VALUES (5, N'Friday')
GO
INSERT [dbo].[DayOfWeek] ([DayOfWeekID], [nameOfDay]) VALUES (6, N'Saturday')
GO
ALTER TABLE [dbo].[CarPools] ADD  CONSTRAINT [DF_CarPools_seatsAvailable]  DEFAULT ((1)) FOR [seatsAvailable]
GO
ALTER TABLE [dbo].[CarPools] ADD  CONSTRAINT [DF_CarPools_created]  DEFAULT (getdate()) FOR [created]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_active]  DEFAULT ((1)) FOR [active]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_created]  DEFAULT (getdate()) FOR [created]
GO
ALTER TABLE [dbo].[CarPoolDays]  WITH CHECK ADD  CONSTRAINT [FK_CarPoolDays_CarPools] FOREIGN KEY([CarPoolID])
REFERENCES [dbo].[CarPools] ([CarPoolID])
GO
ALTER TABLE [dbo].[CarPoolDays] CHECK CONSTRAINT [FK_CarPoolDays_CarPools]
GO
ALTER TABLE [dbo].[CarPoolDays]  WITH CHECK ADD  CONSTRAINT [FK_CarPoolDays_DayOfWeek] FOREIGN KEY([DayOfWeekID])
REFERENCES [dbo].[DayOfWeek] ([DayOfWeekID])
GO
ALTER TABLE [dbo].[CarPoolDays] CHECK CONSTRAINT [FK_CarPoolDays_DayOfWeek]
GO
ALTER TABLE [dbo].[CarPools]  WITH CHECK ADD  CONSTRAINT [FK_CarPools_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[CarPools] CHECK CONSTRAINT [FK_CarPools_Users]
GO
USE [master]
GO
ALTER DATABASE [CoMute] SET  READ_WRITE 
GO
