//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPoolDays
    {
        public int ID { get; set; }
        public int CarPoolID { get; set; }
        public int DayOfWeek { get; set; }
    
        public virtual CarPools CarPools { get; set; }
    }
}
