//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPools()
        {
            this.CarPoolDays = new HashSet<CarPoolDays>();
        }
    
        public int ID { get; set; }
        public int OwnerID { get; set; }
        public string Origin { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ETA { get; set; }
        public string Destination { get; set; }
        public int AvailableSeats { get; set; }
        public string Notes { get; set; }
        public byte[] DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarPoolDays> CarPoolDays { get; set; }
        public virtual CarPools CarPools1 { get; set; }
        public virtual CarPools CarPools2 { get; set; }
    }
}
