//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarPool()
        {
            this.Participants = new HashSet<Participant>();
        }
    
        public int Id { get; set; }
        public System.TimeSpan Depart { get; set; }
        public System.TimeSpan Arrive { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public int DaysAvailable { get; set; }
        public int Seats { get; set; }
        public int HostUserId { get; set; }
        public string Notes { get; set; }
        public bool Active { get; set; }
        public System.DateTime CDate { get; set; }
        public System.Data.Entity.Spatial.DbGeography OriginCoords { get; set; }
        public System.Data.Entity.Spatial.DbGeography DestinationCoords { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual User User { get; set; }
    }
}
