//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMute.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CarPoolId { get; set; }
        public int DaysAvailable { get; set; }
        public bool Active { get; set; }
        public System.DateTime CDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual CarPool CarPool { get; set; }
    }
}
